### PR TITLE
Switch from Travis to GithubActions

### PR DESCRIPTION
**Pull request by n-rodriguez**
And run tests with recent Ruby versions. Thank you!

### CODE REVIEW

**Comment by n-rodriguez** [comment]
Results : https://github.com/n-rodriguez/device_detector/actions/runs/1419211588

**Comment by n-rodriguez** [comment]
hi there! any news?

**Comment by n-rodriguez** [comment]
hi there! any news?

**Comment by silva96** [comment]
hi there, any news?

**Pull request merged**
