### PR TITLE
Give regexes their own cache

### PR DESCRIPTION
**Pull request by seandilda**
This keeps regexes from being uncached after a large number of user agents are processed
Also add an option to forcibly purge the user agent (or regex) cache.  This is useful for long running processes that don't want to keep the cache around.

### CODE REVIEW

**Comment by yagooar** [comment]
Could you please make sure that the tests pass?

**Comment by dukex** [comment]
@yagooar the tests is broken because a strange problems in rbx-2

**Comment by yagooar** [comment]
I'm not sure if supporting Rubinius is actually required. I myself personally don't know much about it and don't have the time to try and fix the issue. Any other opinions?

**Comment by yagooar** [comment]
Could you please rebase with `develop`? I removed Rubinius support so the tests should be passing now. Thanks.

**Comment by yagooar** [comment]
Thanks a lot. Could you please add a small paragraph explaining the two caches and their roles? It'd make it easier for newcomers to understand what they are dealing with (and the reasoning behind separating the two).

**Pull request closed without merging**
