### PR TITLE
Update regexes from piwik

### PR DESCRIPTION
**Pull request by seandilda**

### CODE REVIEW

**Comment by kandadaboggu** [comment]
Will this PR be merged?

**Comment by yagooar** [comment]
Could you please verify the failed tests before merging this? Thanks.

**Comment by yagooar** [comment]
Could you please rebase with `develop`? I removed Rubinius support so the tests should be passing now. Thanks.

**Comment by bradurani** [comment]
Anything I can do to help move this along? ❤️😃 *crosses fingers*

**Comment by yagooar** [comment]
It's perfect as-is, thanks for the contribution!

**Pull request merged**
