### PR TITLE
Add brand for devices

### PR DESCRIPTION
**Pull request by dnswus**
- Add `brand` to device
- Add `device_brand` to device_detector

### CODE REVIEW

**Comment by peteygao** [comment]
Hey @dnswus, the changes look pretty good, but can you follow the existing pattern and add specs for the new method :+1:?

**Comment by dnswus** [comment]
Hi @peteygao, added specs and updated to return `nil` rather than empty string if no brand info.

**Comment by peteygao** [comment]
@yagooar Do you want to take review of this PR and merge it if it's A-Okay?

**Comment by yagooar** [comment]
@dnswus Thanks a lot for the PR!

@peteygao Yes, feel free to review it and once you are done, I will have a quick look and merge it :)

**Comment by peteygao** [comment]
@yagooar Sorry, what I meant was that I already looked at it and now you should take a quick look and merge it :+1:.

**Comment by yagooar** [comment]
Thanks to both of you! I will prepare a new release this weekend :)

**Comment by yagooar** [comment]
@dnswus @peteygao I wanted to let you know that `DeviceDetector 0.8.2` is published on Rubygems now: https://rubygems.org/gems/device_detector/versions/0.8.2 :tada:

**Comment by peteygao** [comment]
👍

**Comment by dnswus** [comment]
:clap:

**Pull request merged**
