### PR TITLE
add RuxitSynthetic bot to regex matches

### PR DESCRIPTION
**Pull request by pmcanneny**
New regex bot match. Thanks

### CODE REVIEW

**Comment by peteygao** [comment]
Thanks for the PR @pmcanneny. Do you happen to have a User Agent of this bot caught in the wild?

**Comment by pmcanneny** [comment]
sure. here is an example:

`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36 RuxitSynthetic/1.0                                                                                                                         `

**Comment by peteygao** [comment]
Thanks @pmcanneny. I'll be sure to test out your changes this weekend!

**Comment by yagooar** [comment]
@peteygao Any progress on this?

**Comment by yagooar** [comment]
@pmcanneny I suggest you push this regex rule to our upstream detection source here: https://github.com/piwik/device-detector

Once it gets merged there, we will get it as well.

**Pull request closed without merging**
