### PR TITLE
Implement vendor fragment parsing - fully implement brand checking in…

### PR DESCRIPTION
**Pull request by seandilda**
… tests

### CODE REVIEW

**Comment by yagooar** [comment]
Could you please rebase with `develop`? I removed Rubinius support so the tests should be passing now. Thanks.

**Comment by bradurani** [comment]
Would ❤️ to see this merged 😃

**Comment by yagooar** [comment]
This is a great contribution, thanks! Could you please add a little documentation as well? It would help newcomers see what the gem can do.

**Comment by yagooar** [comment]
Is there any progress here?

**Comment by yagooar** [comment]
Closing as there hasn't been any feedback since 2017.

**Pull request closed without merging**
