### PR TITLE
Add changelog entry for v1.1.0

### PR DESCRIPTION
**Pull request by girardof**

### CODE REVIEW

**Comment by benzimmer** [comment]
Didn't we want to make this a major version change?

**Comment by girardof** [comment]
That was indeed suggested, but we don't introduce any breaking changes so I don't see a need to make it a major version bump.

**Comment by benzimmer** [comment]
Doesn't removing an old ruby version count?

**Comment by girardof** [comment]
It's debatable, funny enough I stumble upon this very topic this morning on [Nokogiri's website](https://nokogiri.org/#semantic-versioning-policy). 

For our case I don't have strong opinion about the version, let me know what's your preference and I will update the PR accordingly 😉.

**Pull request merged**
