### PR TITLE
fix(Parser): remove redundant nested repeat operator and escape bracket

### LINKED ISSUE #89: Ruby warnings
Hi there!

Since release 1.0.6 I get this warning :

```sh
/cache/nicolas/concerto/ruby-master/ruby/3.0.0/gems/device_detector-1.0.6/lib/device_detector/parser.rb:88: warning: regular expression has ']' without escape
/cache/nicolas/concerto/ruby-master/ruby/3.0.0/gems/device_detector-1.0.6/lib/device_detector/parser.rb:88: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression
```

Thank you!

### PR DESCRIPTION
**Pull request by hendrixfan**
- with ruby 2.7.3 I get the following warnings(described in #89):

```
lib/device_detector/parser.rb:88: warning: regular expression has ']' without escape
lib/device_detector/parser.rb:88: warning: nested repeat operator '+' and '?' was replaced with '*' in regular expression
```
- I removed the '?' operators where possible and exchanged them for '*'
- closes #89

### CODE REVIEW

**Comment by hendrixfan** [comment]
oh, I just read your disclaimer

> Still, our goal is to use the original, unchanged regex yaml files, in order to mutually benefit from updates and pull request to both the original and the ported versions.

you are not maintaining these Files yourself

**Comment by kwent** [comment]
I think your search and replace replaced stuff you didn't want to modify. 

Screen Shot 2021-11-19 at 9 25 09 PM

**Comment by hendrixfan** [comment]
@kwent sorry for not elaborating on my changes further.
I meant those changes in the Screenshot. Those Bracket Ranges do have redudant Characters: `5033[ADXJEFGMOTXYQS]` X in that case.
I got Ruby warnings about those

**Comment by kwent** [comment]
@podigee what is the plan here ? I don't think upstream repositories will ever update those cause it's language specific. Maybe a middleman script to do the conversation and update one every few months would make that workflow easier.

**Comment by yakschuss** [comment]
Silence on the airwaves 😅

**Comment by aried3r** [comment]
> I don't think upstream repositories will ever update those cause it's language specific.

Are they, though? I believe this change should work the same in both languages. There's only three occurrences (of the initial issue, not the duplicate characters) that I could find, so perhaps they'll accept a PR?

https://github.com/matomo-org/device-detector/blob/ebd8a07e4b69088c0e34f29ec72dc162c34c9264/regexes/device/mobiles.yml#L23244
https://github.com/matomo-org/device-detector/blob/ebd8a07e4b69088c0e34f29ec72dc162c34c9264/regexes/device/mobiles.yml#L23253
https://github.com/matomo-org/device-detector/blob/ebd8a07e4b69088c0e34f29ec72dc162c34c9264/regexes/client/browsers.yml#L2370

**Comment by thinklikeadesigner** [comment]
So are we stuck with the huge block of warnings anytime we run a test? 

Screen Shot 2022-01-04 at 12 58 07 PM

**Comment by Spone** [comment]
I guess we should try to open an issue / PR against https://github.com/matomo-org/device-detector and discuss the changes with their maintainers. If the changes do not break other languages, there may be a chance to get it merged?

**Comment by nickcampbell18** [comment]
@Spone I have raised that ticket here, if anybody wants to +1 it for visibility: https://github.com/matomo-org/device-detector/issues/6990

**Comment by sanchezzzhak** [comment]
Regular expressions have been fixed, but you still need to implement the changes that we made here for OS
https://github.com/matomo-org/device-detector/releases/tag/5.0.0

We now have a validator that is guaranteed not to let bad regular expressions slip through.
Thank you all for participating.

**Comment by marcelgo** [comment]
Thanks everybody. We will provide a new version of the gem soon.

**Pull request closed without merging**
